version: '3.8'

services:
  # 1. Cơ sở dữ liệu Microsoft SQL Server 2019 (MSSQL)
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: aita_mssql
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "AitaPassword123!" # MSSQL yêu cầu mật khẩu phức tạp: chữ hoa, chữ thường, số, ký tự đặc biệt
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql

  # 2. Hàng đợi & Caching Redis
  redis:
    image: redis:7-alpine
    container_name: aita_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mssql_data:
  redis_data:
